name: pipeline-ci
on:
  push:
    branches:
      -  labFinalGio*
      
jobs:

  Build:
    #needs: 'SCA'
    runs-on: 'self-hosted'

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          docker build --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_V3_API_KEY }} -t giosteel/laboratorio-final:latest .


      - name: Build Docker image
        run: docker build -t giosteel88/laboratorio-final:latest .

      - name: Install Grype
        run: |
          brew tap anchore/grype
          brew install grype

      - name: Scan Docker image with Grype
        run: |
          grype giosteel/laboratorio-final -o json > grype-report.json

      - name: Print Grype report
        run: cat grype-report.json
          

      - name: Clean up
        run: rm -f grype-report.json


      - name: Push
        run: |
          docker push giosteel88/laboratorio-final:latest



  Deploy:
    needs: Build
    runs-on: 'self-hosted'

    steps:
      - name: Deploy on Docker
        run: |
          docker run -p 8080:80 --name ${{ github.event.repository.name }} -d giosteel88/laboratorio-final:latest

      - name: Wait for readiness
        run: | 
          sleep 30